ALTER TABLE users
ADD COLUMN reset_token VARCHAR(64) NULL,
ADD COLUMN reset_expires DATETIME NULL,
ADD COLUMN verify_token VARCHAR(64) NULL,
ADD COLUMN verified TINYINT(1) DEFAULT 0,
ADD COLUMN remember_token VARCHAR(64) NULL,
ADD COLUMN last_login DATETIME NULL;